pipeline {
    agent { docker 'maven:3.3.3' }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'tomcat7:run -Dmaven.tomcat.port=8081'
            }
        }
    }
}